# Generated by Django 6.0.7 on 2026-07-25 22:02

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(help_text='Description of the activity', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'activity',
            },
        ),
        migrations.CreateModel(
            name='HydropowerPlant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('loepenummer', models.PositiveIntegerField(help_text='Kraftverk Løpenummer', validators=[django.core.validators.MinValueValidator(1)])),
                ('navn', models.CharField(help_text='Navn', max_length=255)),
                ('vannkraftverk_type', models.CharField(choices=[('K', 'Kraftverk'), ('P', 'Pumpe'), ('PK', 'Pumpekraftverk')], help_text='Kraftverk type', max_length=2)),
                ('hovedeier', models.CharField(help_text='Hovedeier', max_length=255)),
                ('hovedeier_orgnr', models.CharField(help_text='Hovedeier OrgNr', max_length=9)),
                ('fylke', models.CharField(help_text='Fylke', max_length=100)),
                ('fylkesnr', models.PositiveSmallIntegerField(help_text='Fylkesnr', validators=[django.core.validators.MinValueValidator(1)])),
                ('kommune', models.CharField(help_text='Kommune', max_length=100)),
                ('kommunenr', models.PositiveIntegerField(help_text='Kommunenr', validators=[django.core.validators.MinValueValidator(1)])),
                ('forsteutnyttelseavfalletdato', models.PositiveIntegerField(blank=True, help_text='Første utnyttelse av fallet år', null=True, validators=[django.core.validators.MinValueValidator(1800)])),
                ('datoforeldstekraftproduserendedel', models.PositiveIntegerField(blank=True, help_text='År for eldste kraftproduserende del', null=True, validators=[django.core.validators.MinValueValidator(1800)])),
                ('maksytelse', models.FloatField(help_text='Maks ytelse (MW)', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('midprod_91_20', models.FloatField(help_text='Midprod 1991-2020 (GWh)', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('bruttofallhoyde_m', models.FloatField(blank=True, help_text='Brutto fallhøyde (m)', null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('slukeevne', models.FloatField(blank=True, help_text='Slukeevne (m3/s)', null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('enekv', models.FloatField(blank=True, help_text='Enekv (m3/s)', null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('elspotomraadenummer', models.PositiveSmallIntegerField(help_text='Elspot område nummer')),
                ('reginenr', models.CharField(help_text='Regine nr', max_length=50)),
                ('eridrift', models.BooleanField(default=True, help_text='Er i drift')),
                ('idriftdato', models.DateField(blank=True, help_text='I drift dato', null=True)),
                ('konsesjoner', models.TextField(blank=True, help_text='Konsesjoner')),
                ('kraftverkstatus', models.CharField(blank=True, help_text='Kraftverk status', max_length=500)),
                ('nedborsfeltnavn', models.CharField(blank=True, help_text='Nedbørsfeltnavn', max_length=255)),
                ('sppunkt', models.CharField(blank=True, help_text='SPPunkt', max_length=255)),
                ('spsone', models.CharField(blank=True, help_text='SPSone', max_length=255)),
                ('underbygging', models.TextField(blank=True, help_text='Underbygging')),
                ('uteavdrift', models.BooleanField(default=False, help_text='Ute av drift')),
                ('vassdragsomraadeid', models.PositiveIntegerField(help_text='Vassdragsområde ID')),
                ('vassdragsomraadenavn', models.CharField(help_text='Vassdragsområde navn', max_length=255)),
            ],
            options={
                'verbose_name': 'Hydropower Plant',
                'verbose_name_plural': 'Hydropower Plants',
                'db_table': 'hydropower',
                'ordering': ['navn'],
            },
        ),
        migrations.CreateModel(
            name='LegalForm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Koden for organisasjonsform', max_length=20, null=True, unique=True)),
                ('description', models.CharField(help_text='Beskrivelsen for organisasjonsform', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'legal_form',
            },
        ),
        migrations.CreateModel(
            name='ShareholderRegister',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('orgnr', models.CharField(help_text='Organisasjonsnummer', max_length=20)),
                ('selskap', models.CharField(help_text='Navn på selskap beholdningen eies i', max_length=255)),
                ('aksjeklasse', models.CharField(help_text='Aksjeklasse eller isin for aksjeklassen', max_length=100)),
                ('foedselsaar_orgnr', models.CharField(help_text='Fødselsår for aksjonærer identifisert i folkeregisteret eller organisasjonsnummer for selskapsaksjonærer', max_length=9)),
                ('postnr_sted', models.CharField(help_text='Postnummer og poststed for aksjonærer identifisert av folkeregisteret eller av enhetsregisteret', max_length=100)),
                ('landkode', models.CharField(help_text='Landkode', max_length=3)),
                ('navn_aksjonaer', models.CharField(help_text='Navn på aksjonær', max_length=255)),
                ('antall_aksjer', models.IntegerField(help_text='Antall aksjer ved utgangen av inntektsåret')),
                ('antall_aksjer_selskap', models.IntegerField(help_text='Antall aksjer totalt i selskap')),
            ],
            options={
                'verbose_name': 'Aksjonærregister',
                'db_table': 'shareholder_register',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bankruptcy', models.BooleanField(default=False, help_text='Bankruptcy status')),
                ('under_liquidation', models.BooleanField(default=False, help_text='Under liquidation status')),
                ('under_compulsory_liquidation_or_dissolution', models.BooleanField(default=False, help_text='Under compulsory liquidation ordissolution status')),
                ('registered_in_business_register', models.BooleanField(default=False, help_text='Registered in Business Register')),
                ('registered_in_establishment_register', models.BooleanField(default=False, help_text='Registered in Establishment Register')),
                ('registered_in_voluntary_register', models.BooleanField(default=False, help_text='Registered in Voluntary Register')),
                ('last_annual_report_submitted', models.DateTimeField(help_text='Last annual report submitted', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'status',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('m_id', models.CharField(blank=True, max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('land', models.CharField(help_text='Land', max_length=100)),
                ('landkode', models.CharField(help_text='Landkode', max_length=20)),
                ('postnummer', models.CharField(help_text='Postnummer', max_length=20)),
                ('poststed', models.CharField(help_text='Poststed', max_length=100)),
                ('adresse', models.CharField(help_text='Gateadresse', max_length=255)),
                ('kommune', models.CharField(help_text='Kommune', max_length=100)),
                ('kommunenummer', models.CharField(help_text='Kommunenummer', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'address',
                'unique_together': {('land', 'landkode', 'postnummer', 'poststed', 'adresse', 'kommune', 'kommunenummer')},
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Industry code', max_length=10, null=True, unique=True)),
                ('name', models.CharField(help_text='Industry name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of the industry', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'industry',
                'unique_together': {('code', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('navn', models.CharField(help_text='Selskapsnavn', max_length=255)),
                ('organisasjonsnummer', models.CharField(help_text='Organisasjonsnummer', max_length=9, unique=True)),
                ('foundation_date', models.DateField(blank=True, help_text='Stiftelsesdato', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brreg.activity')),
                ('forretningsadresse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Forretningsadresse', to='brreg.address')),
                ('postadresse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Postadresse', to='brreg.address')),
                ('industry', models.ManyToManyField(blank=True, to='brreg.industry')),
                ('legal_form', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='brreg.legalform')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='brreg.status')),
            ],
            options={
                'db_table': 'company',
            },
        ),
    ]
